# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EcommerceCustomer4(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'email_address': 'str',
        'opt_in_status': 'bool',
        'company': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'address': 'Address'
    }

    attribute_map = {
        'id': 'id',
        'email_address': 'email_address',
        'opt_in_status': 'opt_in_status',
        'company': 'company',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'address': 'address'
    }

    def __init__(self, id=None, email_address=None, opt_in_status=None, company=None, first_name=None, last_name=None, address=None):  # noqa: E501
        """EcommerceCustomer4 - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._email_address = None
        self._opt_in_status = None
        self._company = None
        self._first_name = None
        self._last_name = None
        self._address = None
        self.discriminator = None

        self.id = id
        self.email_address = email_address
        self.opt_in_status = opt_in_status
        if company is not None:
            self.company = company
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if address is not None:
            self.address = address

    @property
    def id(self):
        """Gets the id of this EcommerceCustomer4.  # noqa: E501

        A unique identifier for the customer. Limited to 50 characters.  # noqa: E501

        :return: The id of this EcommerceCustomer4.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EcommerceCustomer4.

        A unique identifier for the customer. Limited to 50 characters.  # noqa: E501

        :param id: The id of this EcommerceCustomer4.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) > 50:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `50`")  # noqa: E501

        self._id = id

    @property
    def email_address(self):
        """Gets the email_address of this EcommerceCustomer4.  # noqa: E501

        The customer's email address.  # noqa: E501

        :return: The email_address of this EcommerceCustomer4.  # noqa: E501
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address):
        """Sets the email_address of this EcommerceCustomer4.

        The customer's email address.  # noqa: E501

        :param email_address: The email_address of this EcommerceCustomer4.  # noqa: E501
        :type: str
        """
        if email_address is None:
            raise ValueError("Invalid value for `email_address`, must not be `None`")  # noqa: E501

        self._email_address = email_address

    @property
    def opt_in_status(self):
        """Gets the opt_in_status of this EcommerceCustomer4.  # noqa: E501

        The customer's opt-in status. This value will never overwrite the opt-in status of a pre-existing Mailchimp list member, but will apply to list members that are added through the e-commerce API endpoints. Customers who don't opt in to your Mailchimp list [will be added as `Transactional` members](https://mailchimp.com/developer/marketing/docs/e-commerce/#customers).  # noqa: E501

        :return: The opt_in_status of this EcommerceCustomer4.  # noqa: E501
        :rtype: bool
        """
        return self._opt_in_status

    @opt_in_status.setter
    def opt_in_status(self, opt_in_status):
        """Sets the opt_in_status of this EcommerceCustomer4.

        The customer's opt-in status. This value will never overwrite the opt-in status of a pre-existing Mailchimp list member, but will apply to list members that are added through the e-commerce API endpoints. Customers who don't opt in to your Mailchimp list [will be added as `Transactional` members](https://mailchimp.com/developer/marketing/docs/e-commerce/#customers).  # noqa: E501

        :param opt_in_status: The opt_in_status of this EcommerceCustomer4.  # noqa: E501
        :type: bool
        """
        if opt_in_status is None:
            raise ValueError("Invalid value for `opt_in_status`, must not be `None`")  # noqa: E501

        self._opt_in_status = opt_in_status

    @property
    def company(self):
        """Gets the company of this EcommerceCustomer4.  # noqa: E501

        The customer's company.  # noqa: E501

        :return: The company of this EcommerceCustomer4.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this EcommerceCustomer4.

        The customer's company.  # noqa: E501

        :param company: The company of this EcommerceCustomer4.  # noqa: E501
        :type: str
        """

        self._company = company

    @property
    def first_name(self):
        """Gets the first_name of this EcommerceCustomer4.  # noqa: E501

        The customer's first name.  # noqa: E501

        :return: The first_name of this EcommerceCustomer4.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this EcommerceCustomer4.

        The customer's first name.  # noqa: E501

        :param first_name: The first_name of this EcommerceCustomer4.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this EcommerceCustomer4.  # noqa: E501

        The customer's last name.  # noqa: E501

        :return: The last_name of this EcommerceCustomer4.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this EcommerceCustomer4.

        The customer's last name.  # noqa: E501

        :param last_name: The last_name of this EcommerceCustomer4.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def address(self):
        """Gets the address of this EcommerceCustomer4.  # noqa: E501


        :return: The address of this EcommerceCustomer4.  # noqa: E501
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this EcommerceCustomer4.


        :param address: The address of this EcommerceCustomer4.  # noqa: E501
        :type: Address
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcommerceCustomer4, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcommerceCustomer4):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
