# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EmailClient(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client': 'str',
        'members': 'int'
    }

    attribute_map = {
        'client': 'client',
        'members': 'members'
    }

    def __init__(self, client=None, members=None):  # noqa: E501
        """EmailClient - a model defined in Swagger"""  # noqa: E501

        self._client = None
        self._members = None
        self.discriminator = None

        if client is not None:
            self.client = client
        if members is not None:
            self.members = members

    @property
    def client(self):
        """Gets the client of this EmailClient.  # noqa: E501

        The name of the email client.  # noqa: E501

        :return: The client of this EmailClient.  # noqa: E501
        :rtype: str
        """
        return self._client

    @client.setter
    def client(self, client):
        """Sets the client of this EmailClient.

        The name of the email client.  # noqa: E501

        :param client: The client of this EmailClient.  # noqa: E501
        :type: str
        """

        self._client = client

    @property
    def members(self):
        """Gets the members of this EmailClient.  # noqa: E501

        The number of subscribed members who used this email client.  # noqa: E501

        :return: The members of this EmailClient.  # noqa: E501
        :rtype: int
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this EmailClient.

        The number of subscribed members who used this email client.  # noqa: E501

        :param members: The members of this EmailClient.  # noqa: E501
        :type: int
        """

        self._members = members

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmailClient, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailClient):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
