# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GalleryFolder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'file_count': 'int',
        'created_at': 'datetime',
        'created_by': 'str',
        'links': 'list[ResourceLink]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'file_count': 'file_count',
        'created_at': 'created_at',
        'created_by': 'created_by',
        'links': '_links'
    }

    def __init__(self, id=None, name=None, file_count=None, created_at=None, created_by=None, links=None):  # noqa: E501
        """GalleryFolder - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._file_count = None
        self._created_at = None
        self._created_by = None
        self._links = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if file_count is not None:
            self.file_count = file_count
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this GalleryFolder.  # noqa: E501

        The unique id for the folder.  # noqa: E501

        :return: The id of this GalleryFolder.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GalleryFolder.

        The unique id for the folder.  # noqa: E501

        :param id: The id of this GalleryFolder.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GalleryFolder.  # noqa: E501

        The name of the folder.  # noqa: E501

        :return: The name of this GalleryFolder.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GalleryFolder.

        The name of the folder.  # noqa: E501

        :param name: The name of this GalleryFolder.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def file_count(self):
        """Gets the file_count of this GalleryFolder.  # noqa: E501

        The number of files in the folder.  # noqa: E501

        :return: The file_count of this GalleryFolder.  # noqa: E501
        :rtype: int
        """
        return self._file_count

    @file_count.setter
    def file_count(self, file_count):
        """Sets the file_count of this GalleryFolder.

        The number of files in the folder.  # noqa: E501

        :param file_count: The file_count of this GalleryFolder.  # noqa: E501
        :type: int
        """

        self._file_count = file_count

    @property
    def created_at(self):
        """Gets the created_at of this GalleryFolder.  # noqa: E501

        The date and time a file was added to the File Manager in ISO 8601 format.  # noqa: E501

        :return: The created_at of this GalleryFolder.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this GalleryFolder.

        The date and time a file was added to the File Manager in ISO 8601 format.  # noqa: E501

        :param created_at: The created_at of this GalleryFolder.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this GalleryFolder.  # noqa: E501

        The username of the profile that created the folder.  # noqa: E501

        :return: The created_by of this GalleryFolder.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this GalleryFolder.

        The username of the profile that created the folder.  # noqa: E501

        :param created_by: The created_by of this GalleryFolder.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def links(self):
        """Gets the links of this GalleryFolder.  # noqa: E501

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :return: The links of this GalleryFolder.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this GalleryFolder.

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :param links: The links of this GalleryFolder.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GalleryFolder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GalleryFolder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
