# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GalleryFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'folder_id': 'int',
        'type': 'str',
        'name': 'str',
        'full_size_url': 'str',
        'thumbnail_url': 'str',
        'size': 'int',
        'created_at': 'datetime',
        'created_by': 'str',
        'width': 'int',
        'height': 'int',
        'links': 'list[ResourceLink]'
    }

    attribute_map = {
        'id': 'id',
        'folder_id': 'folder_id',
        'type': 'type',
        'name': 'name',
        'full_size_url': 'full_size_url',
        'thumbnail_url': 'thumbnail_url',
        'size': 'size',
        'created_at': 'created_at',
        'created_by': 'created_by',
        'width': 'width',
        'height': 'height',
        'links': '_links'
    }

    def __init__(self, id=None, folder_id=None, type=None, name=None, full_size_url=None, thumbnail_url=None, size=None, created_at=None, created_by=None, width=None, height=None, links=None):  # noqa: E501
        """GalleryFile - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._folder_id = None
        self._type = None
        self._name = None
        self._full_size_url = None
        self._thumbnail_url = None
        self._size = None
        self._created_at = None
        self._created_by = None
        self._width = None
        self._height = None
        self._links = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if folder_id is not None:
            self.folder_id = folder_id
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if full_size_url is not None:
            self.full_size_url = full_size_url
        if thumbnail_url is not None:
            self.thumbnail_url = thumbnail_url
        if size is not None:
            self.size = size
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this GalleryFile.  # noqa: E501

        The unique id of the file.  # noqa: E501

        :return: The id of this GalleryFile.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GalleryFile.

        The unique id of the file.  # noqa: E501

        :param id: The id of this GalleryFile.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def folder_id(self):
        """Gets the folder_id of this GalleryFile.  # noqa: E501

        The id of the folder.  # noqa: E501

        :return: The folder_id of this GalleryFile.  # noqa: E501
        :rtype: int
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """Sets the folder_id of this GalleryFile.

        The id of the folder.  # noqa: E501

        :param folder_id: The folder_id of this GalleryFile.  # noqa: E501
        :type: int
        """

        self._folder_id = folder_id

    @property
    def type(self):
        """Gets the type of this GalleryFile.  # noqa: E501

        The type of file in the File Manager.  # noqa: E501

        :return: The type of this GalleryFile.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GalleryFile.

        The type of file in the File Manager.  # noqa: E501

        :param type: The type of this GalleryFile.  # noqa: E501
        :type: str
        """
        allowed_values = ["image", "file"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def name(self):
        """Gets the name of this GalleryFile.  # noqa: E501

        The name of the file.  # noqa: E501

        :return: The name of this GalleryFile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GalleryFile.

        The name of the file.  # noqa: E501

        :param name: The name of this GalleryFile.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def full_size_url(self):
        """Gets the full_size_url of this GalleryFile.  # noqa: E501

        The url of the full-size file.  # noqa: E501

        :return: The full_size_url of this GalleryFile.  # noqa: E501
        :rtype: str
        """
        return self._full_size_url

    @full_size_url.setter
    def full_size_url(self, full_size_url):
        """Sets the full_size_url of this GalleryFile.

        The url of the full-size file.  # noqa: E501

        :param full_size_url: The full_size_url of this GalleryFile.  # noqa: E501
        :type: str
        """

        self._full_size_url = full_size_url

    @property
    def thumbnail_url(self):
        """Gets the thumbnail_url of this GalleryFile.  # noqa: E501

        The url of the thumbnail preview.  # noqa: E501

        :return: The thumbnail_url of this GalleryFile.  # noqa: E501
        :rtype: str
        """
        return self._thumbnail_url

    @thumbnail_url.setter
    def thumbnail_url(self, thumbnail_url):
        """Sets the thumbnail_url of this GalleryFile.

        The url of the thumbnail preview.  # noqa: E501

        :param thumbnail_url: The thumbnail_url of this GalleryFile.  # noqa: E501
        :type: str
        """

        self._thumbnail_url = thumbnail_url

    @property
    def size(self):
        """Gets the size of this GalleryFile.  # noqa: E501

        The size of the file in bytes.  # noqa: E501

        :return: The size of this GalleryFile.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this GalleryFile.

        The size of the file in bytes.  # noqa: E501

        :param size: The size of this GalleryFile.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def created_at(self):
        """Gets the created_at of this GalleryFile.  # noqa: E501

        The date and time a file was added to the File Manager in ISO 8601 format.  # noqa: E501

        :return: The created_at of this GalleryFile.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this GalleryFile.

        The date and time a file was added to the File Manager in ISO 8601 format.  # noqa: E501

        :param created_at: The created_at of this GalleryFile.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this GalleryFile.  # noqa: E501

        The username of the profile that uploaded the file.  # noqa: E501

        :return: The created_by of this GalleryFile.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this GalleryFile.

        The username of the profile that uploaded the file.  # noqa: E501

        :param created_by: The created_by of this GalleryFile.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def width(self):
        """Gets the width of this GalleryFile.  # noqa: E501

        The width of the image.  # noqa: E501

        :return: The width of this GalleryFile.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this GalleryFile.

        The width of the image.  # noqa: E501

        :param width: The width of this GalleryFile.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this GalleryFile.  # noqa: E501

        The height of an image.  # noqa: E501

        :return: The height of this GalleryFile.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this GalleryFile.

        The height of an image.  # noqa: E501

        :param height: The height of this GalleryFile.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def links(self):
        """Gets the links of this GalleryFile.  # noqa: E501

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :return: The links of this GalleryFile.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this GalleryFile.

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :param links: The links of this GalleryFile.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GalleryFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GalleryFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
