# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20011AudienceActivityClicks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'str',
        'clicks': 'int'
    }

    attribute_map = {
        '_date': 'date',
        'clicks': 'clicks'
    }

    def __init__(self, _date=None, clicks=None):  # noqa: E501
        """InlineResponse20011AudienceActivityClicks - a model defined in Swagger"""  # noqa: E501

        self.__date = None
        self._clicks = None
        self.discriminator = None

        if _date is not None:
            self._date = _date
        if clicks is not None:
            self.clicks = clicks

    @property
    def _date(self):
        """Gets the _date of this InlineResponse20011AudienceActivityClicks.  # noqa: E501


        :return: The _date of this InlineResponse20011AudienceActivityClicks.  # noqa: E501
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this InlineResponse20011AudienceActivityClicks.


        :param _date: The _date of this InlineResponse20011AudienceActivityClicks.  # noqa: E501
        :type: str
        """

        self.__date = _date

    @property
    def clicks(self):
        """Gets the clicks of this InlineResponse20011AudienceActivityClicks.  # noqa: E501


        :return: The clicks of this InlineResponse20011AudienceActivityClicks.  # noqa: E501
        :rtype: int
        """
        return self._clicks

    @clicks.setter
    def clicks(self, clicks):
        """Sets the clicks of this InlineResponse20011AudienceActivityClicks.


        :param clicks: The clicks of this InlineResponse20011AudienceActivityClicks.  # noqa: E501
        :type: int
        """

        self._clicks = clicks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20011AudienceActivityClicks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20011AudienceActivityClicks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
