# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2002Apps(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'users': 'list[str]',
        'links': 'list[ResourceLink]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'users': 'users',
        'links': '_links'
    }

    def __init__(self, id=None, name=None, description=None, users=None, links=None):  # noqa: E501
        """InlineResponse2002Apps - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._description = None
        self._users = None
        self._links = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if users is not None:
            self.users = users
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this InlineResponse2002Apps.  # noqa: E501

        The ID for the application.  # noqa: E501

        :return: The id of this InlineResponse2002Apps.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2002Apps.

        The ID for the application.  # noqa: E501

        :param id: The id of this InlineResponse2002Apps.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse2002Apps.  # noqa: E501

        The name of the application.  # noqa: E501

        :return: The name of this InlineResponse2002Apps.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2002Apps.

        The name of the application.  # noqa: E501

        :param name: The name of this InlineResponse2002Apps.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this InlineResponse2002Apps.  # noqa: E501

        A short description of the application.  # noqa: E501

        :return: The description of this InlineResponse2002Apps.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse2002Apps.

        A short description of the application.  # noqa: E501

        :param description: The description of this InlineResponse2002Apps.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def users(self):
        """Gets the users of this InlineResponse2002Apps.  # noqa: E501

        An array of usernames for users who have linked the app.  # noqa: E501

        :return: The users of this InlineResponse2002Apps.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this InlineResponse2002Apps.

        An array of usernames for users who have linked the app.  # noqa: E501

        :param users: The users of this InlineResponse2002Apps.  # noqa: E501
        :type: list[str]
        """

        self._users = users

    @property
    def links(self):
        """Gets the links of this InlineResponse2002Apps.  # noqa: E501

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :return: The links of this InlineResponse2002Apps.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this InlineResponse2002Apps.

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :param links: The links of this InlineResponse2002Apps.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2002Apps, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002Apps):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
