# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InterestCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'list_id': 'str',
        'id': 'str',
        'title': 'str',
        'display_order': 'int',
        'type': 'str',
        'links': 'list[ResourceLink]'
    }

    attribute_map = {
        'list_id': 'list_id',
        'id': 'id',
        'title': 'title',
        'display_order': 'display_order',
        'type': 'type',
        'links': '_links'
    }

    def __init__(self, list_id=None, id=None, title=None, display_order=None, type=None, links=None):  # noqa: E501
        """InterestCategory - a model defined in Swagger"""  # noqa: E501

        self._list_id = None
        self._id = None
        self._title = None
        self._display_order = None
        self._type = None
        self._links = None
        self.discriminator = None

        if list_id is not None:
            self.list_id = list_id
        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if display_order is not None:
            self.display_order = display_order
        if type is not None:
            self.type = type
        if links is not None:
            self.links = links

    @property
    def list_id(self):
        """Gets the list_id of this InterestCategory.  # noqa: E501

        The unique list id for the category.  # noqa: E501

        :return: The list_id of this InterestCategory.  # noqa: E501
        :rtype: str
        """
        return self._list_id

    @list_id.setter
    def list_id(self, list_id):
        """Sets the list_id of this InterestCategory.

        The unique list id for the category.  # noqa: E501

        :param list_id: The list_id of this InterestCategory.  # noqa: E501
        :type: str
        """

        self._list_id = list_id

    @property
    def id(self):
        """Gets the id of this InterestCategory.  # noqa: E501

        The id for the interest category.  # noqa: E501

        :return: The id of this InterestCategory.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InterestCategory.

        The id for the interest category.  # noqa: E501

        :param id: The id of this InterestCategory.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this InterestCategory.  # noqa: E501

        The text description of this category. This field appears on signup forms and is often phrased as a question.  # noqa: E501

        :return: The title of this InterestCategory.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InterestCategory.

        The text description of this category. This field appears on signup forms and is often phrased as a question.  # noqa: E501

        :param title: The title of this InterestCategory.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def display_order(self):
        """Gets the display_order of this InterestCategory.  # noqa: E501

        The order that the categories are displayed in the list. Lower numbers display first.  # noqa: E501

        :return: The display_order of this InterestCategory.  # noqa: E501
        :rtype: int
        """
        return self._display_order

    @display_order.setter
    def display_order(self, display_order):
        """Sets the display_order of this InterestCategory.

        The order that the categories are displayed in the list. Lower numbers display first.  # noqa: E501

        :param display_order: The display_order of this InterestCategory.  # noqa: E501
        :type: int
        """

        self._display_order = display_order

    @property
    def type(self):
        """Gets the type of this InterestCategory.  # noqa: E501

        Determines how this category’s interests appear on signup forms.  # noqa: E501

        :return: The type of this InterestCategory.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InterestCategory.

        Determines how this category’s interests appear on signup forms.  # noqa: E501

        :param type: The type of this InterestCategory.  # noqa: E501
        :type: str
        """
        allowed_values = ["checkboxes", "dropdown", "radio", "hidden"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def links(self):
        """Gets the links of this InterestCategory.  # noqa: E501

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :return: The links of this InterestCategory.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this InterestCategory.

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :param links: The links of this InterestCategory.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterestCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterestCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
