# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Outreach(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'published_time': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'published_time': 'published_time'
    }

    def __init__(self, id=None, name=None, type=None, published_time=None):  # noqa: E501
        """Outreach - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._type = None
        self._published_time = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if published_time is not None:
            self.published_time = published_time

    @property
    def id(self):
        """Gets the id of this Outreach.  # noqa: E501

        A unique identifier for the outreach. Can be an email campaign ID.  # noqa: E501

        :return: The id of this Outreach.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Outreach.

        A unique identifier for the outreach. Can be an email campaign ID.  # noqa: E501

        :param id: The id of this Outreach.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Outreach.  # noqa: E501

        The name for the outreach.  # noqa: E501

        :return: The name of this Outreach.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Outreach.

        The name for the outreach.  # noqa: E501

        :param name: The name of this Outreach.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this Outreach.  # noqa: E501

        The type of the outreach.  # noqa: E501

        :return: The type of this Outreach.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Outreach.

        The type of the outreach.  # noqa: E501

        :param type: The type of this Outreach.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def published_time(self):
        """Gets the published_time of this Outreach.  # noqa: E501

        The date and time the Outreach was published in ISO 8601 format.  # noqa: E501

        :return: The published_time of this Outreach.  # noqa: E501
        :rtype: datetime
        """
        return self._published_time

    @published_time.setter
    def published_time(self, published_time):
        """Sets the published_time of this Outreach.

        The date and time the Outreach was published in ISO 8601 format.  # noqa: E501

        :param published_time: The published_time of this Outreach.  # noqa: E501
        :type: datetime
        """

        self._published_time = published_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Outreach, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Outreach):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
