# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SalesforceCRMTracking1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'campaign': 'bool',
        'notes': 'bool'
    }

    attribute_map = {
        'campaign': 'campaign',
        'notes': 'notes'
    }

    def __init__(self, campaign=None, notes=None):  # noqa: E501
        """SalesforceCRMTracking1 - a model defined in Swagger"""  # noqa: E501

        self._campaign = None
        self._notes = None
        self.discriminator = None

        if campaign is not None:
            self.campaign = campaign
        if notes is not None:
            self.notes = notes

    @property
    def campaign(self):
        """Gets the campaign of this SalesforceCRMTracking1.  # noqa: E501

        Create a campaign in a connected Salesforce account.  # noqa: E501

        :return: The campaign of this SalesforceCRMTracking1.  # noqa: E501
        :rtype: bool
        """
        return self._campaign

    @campaign.setter
    def campaign(self, campaign):
        """Sets the campaign of this SalesforceCRMTracking1.

        Create a campaign in a connected Salesforce account.  # noqa: E501

        :param campaign: The campaign of this SalesforceCRMTracking1.  # noqa: E501
        :type: bool
        """

        self._campaign = campaign

    @property
    def notes(self):
        """Gets the notes of this SalesforceCRMTracking1.  # noqa: E501

        Update contact notes for a campaign based on subscriber email addresses.  # noqa: E501

        :return: The notes of this SalesforceCRMTracking1.  # noqa: E501
        :rtype: bool
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this SalesforceCRMTracking1.

        Update contact notes for a campaign based on subscriber email addresses.  # noqa: E501

        :param notes: The notes of this SalesforceCRMTracking1.  # noqa: E501
        :type: bool
        """

        self._notes = notes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SalesforceCRMTracking1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SalesforceCRMTracking1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
