# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SendChecklist(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_ready': 'bool',
        'items': 'list[SendChecklistItems]',
        'links': 'list[ResourceLink]'
    }

    attribute_map = {
        'is_ready': 'is_ready',
        'items': 'items',
        'links': '_links'
    }

    def __init__(self, is_ready=None, items=None, links=None):  # noqa: E501
        """SendChecklist - a model defined in Swagger"""  # noqa: E501

        self._is_ready = None
        self._items = None
        self._links = None
        self.discriminator = None

        if is_ready is not None:
            self.is_ready = is_ready
        if items is not None:
            self.items = items
        if links is not None:
            self.links = links

    @property
    def is_ready(self):
        """Gets the is_ready of this SendChecklist.  # noqa: E501

        Whether the campaign is ready to send.  # noqa: E501

        :return: The is_ready of this SendChecklist.  # noqa: E501
        :rtype: bool
        """
        return self._is_ready

    @is_ready.setter
    def is_ready(self, is_ready):
        """Sets the is_ready of this SendChecklist.

        Whether the campaign is ready to send.  # noqa: E501

        :param is_ready: The is_ready of this SendChecklist.  # noqa: E501
        :type: bool
        """

        self._is_ready = is_ready

    @property
    def items(self):
        """Gets the items of this SendChecklist.  # noqa: E501

        A list of feedback items to review before sending your campaign.  # noqa: E501

        :return: The items of this SendChecklist.  # noqa: E501
        :rtype: list[SendChecklistItems]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this SendChecklist.

        A list of feedback items to review before sending your campaign.  # noqa: E501

        :param items: The items of this SendChecklist.  # noqa: E501
        :type: list[SendChecklistItems]
        """

        self._items = items

    @property
    def links(self):
        """Gets the links of this SendChecklist.  # noqa: E501

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :return: The links of this SendChecklist.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SendChecklist.

        A list of link types and descriptions for the API schema documents.  # noqa: E501

        :param links: The links of this SendChecklist.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SendChecklist, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendChecklist):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
