# coding: utf-8

"""
    Mailchimp Marketing API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.74
    Contact: apihelp@mailchimp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UpdateInformationAboutASpecificWorkflowEmail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'settings': 'CampaignSettings1',
        'delay': 'AutomationDelay1'
    }

    attribute_map = {
        'settings': 'settings',
        'delay': 'delay'
    }

    def __init__(self, settings=None, delay=None):  # noqa: E501
        """UpdateInformationAboutASpecificWorkflowEmail - a model defined in Swagger"""  # noqa: E501

        self._settings = None
        self._delay = None
        self.discriminator = None

        if settings is not None:
            self.settings = settings
        if delay is not None:
            self.delay = delay

    @property
    def settings(self):
        """Gets the settings of this UpdateInformationAboutASpecificWorkflowEmail.  # noqa: E501


        :return: The settings of this UpdateInformationAboutASpecificWorkflowEmail.  # noqa: E501
        :rtype: CampaignSettings1
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this UpdateInformationAboutASpecificWorkflowEmail.


        :param settings: The settings of this UpdateInformationAboutASpecificWorkflowEmail.  # noqa: E501
        :type: CampaignSettings1
        """

        self._settings = settings

    @property
    def delay(self):
        """Gets the delay of this UpdateInformationAboutASpecificWorkflowEmail.  # noqa: E501


        :return: The delay of this UpdateInformationAboutASpecificWorkflowEmail.  # noqa: E501
        :rtype: AutomationDelay1
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """Sets the delay of this UpdateInformationAboutASpecificWorkflowEmail.


        :param delay: The delay of this UpdateInformationAboutASpecificWorkflowEmail.  # noqa: E501
        :type: AutomationDelay1
        """

        self._delay = delay

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateInformationAboutASpecificWorkflowEmail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateInformationAboutASpecificWorkflowEmail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
